import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#2f0404",
        "primary-container": "#4a1815",
        "on-primary": "#ffffff",
        "on-primary-container": "#c67c75",
        secondary: "#755b00",
        "secondary-container": "#fed255",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#735a00",
        "secondary-fixed": "#ffe08e",
        "secondary-fixed-dim": "#ecc246",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#584400",
        surface: "#fff9ef",
        "surface-bright": "#fff9ef",
        "surface-dim": "#dfd9d1",
        "surface-container": "#f3ede4",
        "surface-container-low": "#f9f3ea",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ede7df",
        "surface-container-highest": "#e7e2d9",
        "on-surface": "#1d1b16",
        "on-surface-variant": "#534341",
        "on-background": "#1d1b16",
        background: "#fff9ef",
        tertiary: "#2b0807",
        "tertiary-container": "#451c19",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bd807a",
        outline: "#857371",
        "outline-variant": "#d8c1bf",
        error: "#ba1a1a",
        "inverse-surface": "#32302a",
        "inverse-on-surface": "#f6f0e7",
        "surface-variant": "#e7e2d9",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "Georgia", "serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
      },
      spacing: {
        "2xs": "0.25rem",
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
        "3xl": "4.5rem",
        "4xl": "6rem",
        "5xl": "8rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};

export default config;
